### 🔐 Crear Usuario
POST http://localhost:4000/auth/register
Content-Type: application/json

{
  "handle": "erhc",
  "name": "Edwin",
  "email": "correo3@gmail.com",
  "password": "12345678"
}

###

### 🔑 Iniciar Sesión
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "correo1@correo.com",
  "password": "123456789"
}


### 🔑 Get User
GET http://localhost:4000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2QwMzRiOGM4ZDZiNGM3NWQxNGI4MyIsImlhdCI6MTc0ODk5NTMzNSwiZXhwIjoxNzQ4OTk1OTM1fQ._PbmAyB6atduhfW9CUcc5-CcFvj0Kw6TLmzr5vz8Yjo

